# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63d074f003a7f4e40024084d17700feb169572c00b800c9e99438dc630525953727fd4bea4f740fbea1637d2e617ccdf5919693c954bf1a47acbc024e8a18684

test:
  secret_key_base: 00a3043c011a7b94610f494499eaac1bff7cf466c401077fe7c3169b56967197783a0b2b7e0a4610667b6b1f9743eecf59f8a62880bdf44a456515cbdcfb8511

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
